#!/usr/bin/perl
########################################################
# LiteSpeed webserver : number of hits
# Written by Alex S Grebenschikov (www.poralix.com)
# Created at: Mon Apr  8 10:57:04 CEST 2019
########################################################
# 2022-06-28 - Improved by Dejan (www.dreamweb.rs)
########################################################

if ( $ARGV[0] eq 'autoconf' ) {
   if ( -e '/dev/shm/lsws/status/.rtreport' ) {
      print "yes\n";
      exit;
   } else {
      print "no\n";
      exit 1;
   }
}

if ( $ARGV[0] eq 'config' ) {
    print "graph_title Litespeed : hits\n";
    print "graph_args --base 1000 --lower-limit 0\n";
    print "graph_scale no\n";
    print "graph_vlabel hits\n";
    print "graph_category litespeed\n";

    print "total_hits.label Total Hits\n";
    print "total_hits.type DERIVE\n";
    print "total_hits.draw LINE1\n";
    print "total_hits.min 0\n";

    print "static_hits.label Total Static Hits\n";
    print "static_hits.type DERIVE\n";
    print "static_hits.draw AREA\n";
    print "static_hits.min 0\n";

    print "cache_public.label Total Public Cache Hits\n";
    print "cache_public.type DERIVE\n";
    print "cache_public.draw LINE1\n";
    print "cache_public.min 0\n";

    print "cache_private.label Total Private Cache Hits\n";
    print "cache_private.type DERIVE\n";
    print "cache_private.draw LINE1\n";
    print "cache_private.min 0\n";

    exit 0;
}

if ( ! -e '/dev/shm/lsws/status/.rtreport' ) {
  print "total_hits.value 0\n";
  print "static_hits.value 0\n";
  print "cache_public.value 0\n";
  print "cache_private.value 0\n";
  exit 0;
}

@stats = `ls -a /dev/shm/lsws/status/.rtreport*`;
foreach $rep ( @stats ) {
   open IN, "<$rep";
   while ( <IN> ) {
      if ( /TOT_REQS: (\d+), PUB_CACHE_HITS_PER_SEC: ([0-9]*\.?[0-9]+), TOTAL_PUB_CACHE_HITS: (\d+), PRIVATE_CACHE_HITS_PER_SEC: ([0-9]*\.?[0-9]+), TOTAL_PRIVATE_CACHE_HITS: (\d+), STATIC_HITS_PER_SEC: ([0-9]*\.?[0-9]+), TOTAL_STATIC_HITS: (\d+)/ ) {
        $total_hits += $1;
        $static_hits += $7;
        $cache_public += $3;
        $cache_private += $5;
        last;
      }
   }
   close IN;
}

if ($total_hits le 0) { $total_hits = 0; }
if ($static_hits le 0) { $static_hits = 0; }
if ($cache_public le 0) { $cache_public = 0; }
if ($cache_private le 0) { $cache_private = 0; }

print "total_hits.value $total_hits\n";
print "static_hits.value $static_hits\n";
print "cache_public.value $cache_public\n";
print "cache_private.value $cache_private\n";

exit;
